### ISSUE TITLE
Allocate uncategorised articles

### ISSUE THREAD

**Issue by Dan7vt** [stock2shop/website#23]
Anything issue related into Help Centre the rest go in User Docs

**Comment by flumonion** [comment]
Dan, please clarify what you mean here?

**Comment by Dan7vt** [comment]
All content in `/uncategorised/` to to be categorised under either `/user-docs/` or `/help-centre/`. @flumonion Please confirm if this should include 'features' ( currently only B2B, Shopify & ParcelNinja). It wasn't clear from last correspondence that it should remain under solutions as marketing material? By solutions, do you mean to keep this in FD rather?

**Comment by flumonion** [comment]
@Dan7vt we do not want to categorise uncategorised items.
These should be ignored.
