### ISSUE TITLE
Hierarchy, wikis and the four types of documentation

### ISSUE THREAD

**Issue by mozey** [stock2shop/website#32]
@flumonion  You might be interested in this?

[The tree-based approach to organizing documentation sucks](https://www.worldofbs.com/why-documentation-sucks/)

[4 types of documentation](https://documentation.divio.com/)

**Comment by flumonion** [comment]
Very useful and relevant!

Currently, we have broken down our documentation into:-

- API docs (using [docuapi](https://docuapi.netlify.app/) hugo theme) This will be a subset of only the relevant endpoints from our existing swagger docs. The benefits of this over swagger is it allows for examples and explanations on each endpoint. I also want to hide swagger endpoints that consumers should not know about. I see swagger existing for internal devs.
- How-to
- Solutions (issues and answers)
- Getting started (setup and configuration)

We are not that far off the "4 types of documentation"...
Based on the articles you linked to this may be changed.

I like the idea of not using hierarchy in documentation.
We have tried to do this.
For example, linking to the sources and channels applicable to a solution in the front matter of the content (as tags in an array) rather than some type of hierarchy.
I am sure we can still improve on this dramatically.

**Comment by simonious1989** [comment]
@mozey & @flumonion 

Writing out the documentation can get confusing at times as we have not defined the sections clearly.
There also seems to bit a bit of overlap in some instances.

I like the [4 types of documentation guide](https://documentation.divio.com/introduction/), it makes a lot of sense.
What I have done is listed the types of "documentation" pages and their purpose within the context of Stock2Shop.

The idea is that if something has not yet been documented we can easily place it in the below framework.
I have split the sections up into Marketing and Supporting documentation. 
I know there are many other pages on the website but I am focusing on the documentation side of things.

### Marketing Documentation
| Page                       | Description                                                                                                                                  | Includes                                                                                                                                        | Example (Current Site)                                                                                                       | Example (other site) | Orientaded to | Page Type                                                               |
| -------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------- | -------------------- | ------------- | ----------------------------------------------------------------------- |
| Integrations Page          | Lists all connectors on a single page with a brief description of each connector.                                                            | A list of all connectors that can be filtered by connector type.                                                                                | [https://www.stock2shop.com/integrations/](https://www.stock2shop.com/integrations/)                                         | \-                   | information   | [Reference](https://documentation.divio.com/reference/#reference)       |
| Connector Page             | The connector page list key detail about the specific connector and which channels / marketplace / fulfilment service it can integrate with. | \- Sync products<br>\- Sync customers<br>\- Raise orders<br>\- Send fulfilments                                                                 | [https://www.stock2shop.com/integrations/sap/](https://www.stock2shop.com/integrations/sap/)                                 | \-                   | understanding | [Explanation](https://documentation.divio.com/explanation/#explanation) |
| Connector Combination Page | The combination page explains specifics about the combination integration                                                                    | \- Sync products & vairants<br>\- Sync customers<br>\- Sync multiple price lists<br>\- Sync multiple warehouses<br>\- Sync contract pricing<br> | [https://www.stock2shop.com/integrations/sap-b2b-trade-store/](https://www.stock2shop.com/integrations/sap-b2b-trade-store/) | \-                   | understanding | [Explanation](https://documentation.divio.com/explanation/#explanation) |

### Supporting Documentation
| Page            | Description                                                                                                                                                                                                                                                                                                                                                 | Includes                                                                                                                                                                                                                                                                                       | Example (Current Site)                                                                                       | Example (other site)                                                                   | Orientaded to | Page Type     |
| --------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------- | ------------- | ------------- |
| Getting Started | A basic guide on getting started (integrating) with Stock2Shop. What you will need and what our process is. This is an explanation of stock2shop and not an explanation about getting started with the various connectors.                                                                                                                                  | 1\. Getting started with S2S<br>2\. What is S2S<br>3\. Ways in which to "Install" S2S<br>4\. Whats next<br>                                                                                                                                                                                    | Does not exist                                                                                               | [https://segment.com/docs/getting-started/](https://segment.com/docs/getting-started/) | understanding | Explanation   |
| Guides          | Understaind the S2S landscape. This could possibly include the different types of business models and how S2S can be used to make life easier.<br>Guides explain the various general features of the S2S system (Key concepts) that would typically exist with every integration. More specific connector features should be explained under the connector. | Models<br>\- Retail<br>\- wholesale<br>\- Retail & Wholsale<br>\- Dropshipping<br><br>Key Concepts<br>\- Console<br>\- Dashboard<br>\- Customers<br>\- Orders<br>\- Products<br>\- Queue<br>\- Settings > Notifications<br><br>\- Products<br>\- Sources<br>\- Channels<br>\- Fulfillments<br> | Exists in various places on the current website                                                              | [https://segment.com/docs/guides/](https://segment.com/docs/guides/)                   | understanding | Explanation   |
| Connectors      | This will have the following sub sections:<br>                                                                                                                                                                                                                                                                                                              | \- Getting Started<br>\- Features of this connector<br>\- Solutions<br>\- Guides                                                                                                                                                                                                               | Exists in various places on the current website. I am proposing that this be in one section.                 | \-                                                                                     | a goal        | how-to guides |
| Glossary        | Succinct description of terminiolgy directed related to or used in the S2S ecosystem                                                                                                                                                                                                                                                                        | \- Source<br>\- Channel<br>\- System<br><br>                                                                                                                                                                                                                                                   | currently does I exist, but I believe it should be part of documentation and we need to add to it.           | [https://segment.com/docs/glossary/](https://segment.com/docs/glossary/)               | information   | Reference     |
| Developers      | Documentation relating specifically to making use of the S2S API.<br>                                                                                                                                                                                                                                                                                       | \- Authenticating<br>\- Products<br>\- Customers<br>\- Orders<br>                                                                                                                                                                                                                              | [https://www.stock2shop.com/documentation/developers/](https://www.stock2shop.com/documentation/developers/) | [https://reference.segmentapis.com/#intro](https://reference.segmentapis.com/#intro)   | learning      | Tutorials     |

I would like to use this (or something similar) as a guideline for completing the new website documentation.
It should also make it easier to know what documentation we are missing.

In terms of how this would work on Hugo.
Each one of thee supporting document sections could be one .md file, i.e:

   - getting_started.md
   - guides.md
   - connectors.md
   - glossary.md
   - developers.md

If we are referencing something relating to the aforementioned .md files on other pages, 
we can use anchors to link directly to that part of the page.
Alternatively, each aforementioned section can be its own directory with multiple .md files.

**Comment by simonious1989** [comment]
@flumonion & @mozey 

Could we set some time up to discuss this or at least confirm on this issue.
We are nearing the point of selecting a designer for the site theme.

I would like to use this time to structure and work on the documentation.

**Comment by mozey** [comment]
> Could we set some time up to discuss this

Sure, let me know when in advance so I have time to read through everything

**Comment by simonious1989** [comment]
@mozey @flumonion 

ok thanks, will set up a meeting for Thursday this week to run through it.

**Comment by simonious1989** [comment]
@flumonion @mozey @mannyqi @jasonsaayman @adamcannell 

To confirm, we are going to keep the documentation (help) directory structure as-is:

- help 
  - getting-started
  - how-to
  - solutions

on the root (/help) each connector will have its own .md file (i.e dolfin.md, sap.md) 
where all supporting documentation for a single source / connector will be consolidated.

**Comment by mozey** [comment]
That makes sense.

Re. the tags, I would suggest just using a property called "tags", instead of trying to separate them into "source" and "channel"?

For background, the reason why we have the "source" and "channel" concepts instead of just "connector", is to make data flow explicit. That is
- product data is read from the source and synced to the channel
- orders are received from the channel and synced to the source

By definition this avoid loops. For example, if you could configure the same connector as both a source and a channel, it might sync the same order to itself over and over.

But in the documentation it's ok if you talk about a "connector". If it's an ERP (SAP), then obviously it's a source. If it's an e-commerce platform (Takealot) then it must be a channel. Sure, we might create a Takealot source in the system, but that will be an exception case. Usually the connector is either a source or a channel.

Taking above example you might tag an article as below, "_source" is only appended if clarification is necessary
```
tags="sap takealot takealot_source" 
```

Just an idea, let me know if it makes sense

**Comment by mozey** [comment]
Another thing I just thought about, what if an article applies to all sources, or channels, or connectors.  You don't want to update tags  everywhere when adding new connectors. Would you also have collection tags like this
```
tags="source"
tags="channel"
tags="connector"
```
