### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by flumonion** [stock2shop/website#40]
@simonious1989 please can someone add pricing to [this file](https://github.com/stock2shop/website/blob/b9dc651c7454f5f70433cad9ff837a7b7b6c154f/themes/s2s/assets/js/functions.js#L184);
It may be best to do it in a separate .json file first and it can be moved across later.

**Comment by simonious1989** [comment]
@flumonion I have completed adding all the connectors to the `priceMap` and committed.

**Comment by simonious1989** [comment]
@flumonion I added additional tiers:

```
- 20000
- 50000
- 100000
```

I also update the pricing/single template to include these tiers the drop down.
