### ISSUE TITLE
Add anchor to solution issue heading

### ISSUE THREAD

**Issue by adamcannell** [stock2shop/website#54]
Currently we are not able to link to specific solutions with a URL.
https://gallant-wing-8fd3e7.netlify.app/help/troubleshooting/orders/

Add [text](link) does not work when adding to the issue (heading of the troubleshooting solution).

@flumonion Do you know if we can link without adding an anchor text in the body?

**Comment by simonious1989** [comment]
@adamcannell 

all issues now live on a separate page. You can now copy page links and send to clients.
