### ISSUE TITLE
Diagrams larger than `section__content` div in guides template

### ISSUE THREAD

**Issue by simonious1989** [stock2shop/website#55]
@flumonion 

Diagrams (drawn on Excalidraw) are larger than the div class `section__content` in the `help > guides` template.
I think the image width must be set to `width: 100%;`.

I have included an example (/help/guides/product/)
<img width="856" alt="Screenshot 2021-12-17 at 15 37 18" src="https://user-images.githubusercontent.com/39789204/146552739-241b75f2-0c96-4881-ae15-394d7a32c9e2.png">

**Comment by mannyqi** [comment]
@simonious1989 

> I think the image width must be set to width: 100%;

Use `max-width: 100%` on the image. This should make the image responsive
